-- ==============================================================================
-- 1. CRIAÇÃO DO SCHEMA E BANCO DE DADOS (Execute conectado no db_brokerlab)
-- ==============================================================================
CREATE SCHEMA IF NOT EXISTS stg_raw;

-- ==============================================================================
-- 2. CRIAÇÃO DAS TABELAS (Todas as colunas como TEXT para segurança na ingestão)
-- ==============================================================================
-- Layout oficial gerado a partir dos headers dos CSVs de PRD em:
-- /Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw
--
-- O COPY abaixo depende da ordem das colunas. Portanto, cada tabela é criada
-- exatamente na ordem do header oficial do respectivo arquivo CSV.
--
-- Observação: os arquivos podem vir com BOM UTF-8 no primeiro header. O COPY
-- com HEADER ignora a linha de cabeçalho; validações por nome devem ler os
-- arquivos com utf-8-sig ou remover o BOM antes de comparar headers.

DROP TABLE IF EXISTS
    stg_raw.crm_account_base,
    stg_raw.crm_user_base,
    stg_raw.lv_tpaccountbase,
    stg_raw.lv_monetarytransactionbase,
    stg_raw.sirix_daily_view,
    stg_raw.sirix_trades_view,
    stg_raw.sirix_users_view;

-- 2.1 CRM Account Base (28 colunas)
CREATE TABLE stg_raw.crm_account_base (
    "Name" TEXT,
    "CreatedOn" TEXT,
    "ModifiedOn" TEXT,
    "AccountId" TEXT,
    "OwnerId" TEXT,
    "OwningBusinessUnit" TEXT,
    "Lv_Affiliate" TEXT,
    "Lv_campaignId" TEXT,
    "lv_conversionownerid" TEXT,
    "lv_countryid" TEXT,
    "Lv_FirstName" TEXT,
    "Lv_FTDExist" TEXT,
    "Lv_Language" TEXT,
    "Lv_LastName" TEXT,
    "Lv_LeadStatus" TEXT,
    "Lv_LeadStatusReason" TEXT,
    "lv_maintpaccountid" TEXT,
    "lv_retentionownerid" TEXT,
    "lv_SourceID" TEXT,
    "Lv_SubAffiliate" TEXT,
    "Country" TEXT,
    "BUName" TEXT,
    "Parent" TEXT,
    "Conversion Owner" TEXT,
    "Retention Owner" TEXT,
    "Conversion BU" TEXT,
    "Retention BU" TEXT,
    "LeadStatusText" TEXT
);

-- 2.2 CRM User Base (132 colunas)
CREATE TABLE stg_raw.crm_user_base (
    "IncomingEmailDeliveryMethod" TEXT,
    "YammerUserId" TEXT,
    "PersonalEMailAddress" TEXT,
    "DefaultMailbox" TEXT,
    "YammerEmailAddress" TEXT,
    "UserLicenseType" TEXT,
    "OrganizationId" TEXT,
    "MobileOfflineProfileId" TEXT,
    "ApplicationIdUri" TEXT,
    "PreferredEmailCode" TEXT,
    "ModifiedOn" TEXT,
    "ModifiedBy" TEXT,
    "IsDisabled" TEXT,
    "CreatedOnBehalfBy" TEXT,
    "IdentityId" TEXT,
    "IsActiveDirectoryUser" TEXT,
    "MiddleName" TEXT,
    "BusinessUnitId" TEXT,
    "HomePhone" TEXT,
    "DisabledReason" TEXT,
    "DefaultOdbFolderName" TEXT,
    "TimeZoneRuleVersionNumber" TEXT,
    "MobileAlertEMail" TEXT,
    "AzureActiveDirectoryObjectId" TEXT,
    "EmployeeId" TEXT,
    "PreferredAddressCode" TEXT,
    "InternalEMailAddress" TEXT,
    "OverriddenCreatedOn" TEXT,
    "OutgoingEmailDeliveryMethod" TEXT,
    "IsSyncWithDirectory" TEXT,
    "ModifiedOnBehalfBy" TEXT,
    "PhotoUrl" TEXT,
    "DisplayInServiceViews" TEXT,
    "TransactionCurrencyId" TEXT,
    "LastName" TEXT,
    "SetupUser" TEXT,
    "JobTitle" TEXT,
    "NickName" TEXT,
    "MobilePhone" TEXT,
    "DefaultFiltersPopulated" TEXT,
    "DomainName" TEXT,
    "ParentSystemUserId" TEXT,
    "SystemUserId" TEXT,
    "CreatedBy" TEXT,
    "FullName" TEXT,
    "EmailRouterAccessApproval" TEXT,
    "Salutation" TEXT,
    "ImportSequenceNumber" TEXT,
    "AccessMode" TEXT,
    "CreatedOn" TEXT,
    "PreferredPhoneCode" TEXT,
    "InviteStatusCode" TEXT,
    "SharePointEmailAddress" TEXT,
    "CalendarId" TEXT,
    "Skills" TEXT,
    "ExchangeRate" TEXT,
    "WindowsLiveID" TEXT,
    "IsEmailAddressApprovedByO365Admin" TEXT,
    "ApplicationId" TEXT,
    "CALType" TEXT,
    "IsLicensed" TEXT,
    "FirstName" TEXT,
    "UTCConversionTimeZoneCode" TEXT,
    "PositionId" TEXT,
    "ProcessId" TEXT,
    "QueueId" TEXT,
    "EntityImageId" TEXT,
    "ActiveDirectoryGuid" TEXT,
    "TraversedPath" TEXT,
    "IsIntegrationUser" TEXT,
    "StageId" TEXT,
    "Title" TEXT,
    "PassportHi" TEXT,
    "PassportLo" TEXT,
    "GovernmentId" TEXT,
    "YomiMiddleName" TEXT,
    "YomiFullName" TEXT,
    "YomiLastName" TEXT,
    "YomiFirstName" TEXT,
    "LatestUpdateTime" TEXT,
    "UserPuid" TEXT,
    "TerritoryId" TEXT,
    "SiteId" TEXT,
    "msdyn_gdproptout" TEXT,
    "lv_AtomixAgentId" TEXT,
    "lv_CallExtension" TEXT,
    "Lv_CanCreateTPAccount" TEXT,
    "Lv_CanDeleteTPAccount" TEXT,
    "Lv_candisableenableTPaccount" TEXT,
    "Lv_CanExportReports" TEXT,
    "Lv_CanHandleTransactions" TEXT,
    "Lv_CanPrintReports" TEXT,
    "Lv_CanUseCustomDeposit" TEXT,
    "lv_EnableHideEmailContent" TEXT,
    "lv_hidepopupalertsonmarginstatus" TEXT,
    "Lv_IsActive" TEXT,
    "lv_IsBusinessUnitOwner" TEXT,
    "Lv_IsConversionOwner" TEXT,
    "Lv_IsRetentionOwner" TEXT,
    "lv_issystemuser" TEXT,
    "lv_LeadAssignmentFrequency" TEXT,
    "lv_LeadAssignmentLogicCalculationCounter" TEXT,
    "lv_LeadStatusLimitation" TEXT,
    "lv_livechat_groupid" TEXT,
    "Lv_ManagementReportVisibility" TEXT,
    "lv_OmnichannelAgentID" TEXT,
    "lv_password" TEXT,
    "lv_RecentAssignmentQueue" TEXT,
    "Lv_ReportVisibility" TEXT,
    "lv_RolesManagement" TEXT,
    "lv_ShouldShow2FA" TEXT,
    "lv_ViewAggregatedAccountStatusReport" TEXT,
    "Lv_ViewBusinessUnitManagementReport" TEXT,
    "Lv_ViewConversionReport" TEXT,
    "Lv_ViewCreditLineReport" TEXT,
    "lv_ViewMarginStatusHistoryReport" TEXT,
    "Lv_ViewOrganizationManagementReport" TEXT,
    "Lv_ViewRetentionReport" TEXT,
    "Lv_ViewTagReport" TEXT,
    "Lv_ViewTradersforRetentionReport" TEXT,
    "lv_voip_extension" TEXT,
    "lvvoip_enablepopup" TEXT,
    "lvvoip_extension" TEXT,
    "lvvoip_extensionad" TEXT,
    "lvvoip_PopupType" TEXT,
    "lvvoip_apicode" TEXT,
    "lvvoip_provider" TEXT,
    "lv_LogintoClientZoneasAccount" TEXT,
    "lv_ShowWhatsAppButton" TEXT,
    "lv_authenticatorenabled" TEXT,
    "lv_googleauthenticatorsecretkeytemp" TEXT,
    "lv_Isset" TEXT
);

-- 2.3 CRM Lv_tpaccountBase (72 colunas)
CREATE TABLE stg_raw.lv_tpaccountbase (
    "Lv_tpaccountId" TEXT,
    "CreatedOn" TEXT,
    "CreatedBy" TEXT,
    "ModifiedOn" TEXT,
    "ModifiedBy" TEXT,
    "CreatedOnBehalfBy" TEXT,
    "ModifiedOnBehalfBy" TEXT,
    "OwnerId" TEXT,
    "OwnerIdType" TEXT,
    "OwningBusinessUnit" TEXT,
    "statecode" TEXT,
    "statuscode" TEXT,
    "ImportSequenceNumber" TEXT,
    "OverriddenCreatedOn" TEXT,
    "TimeZoneRuleVersionNumber" TEXT,
    "UTCConversionTimeZoneCode" TEXT,
    "Lv_name" TEXT,
    "lv_accountid" TEXT,
    "lv_BalanceBaseCurrency" TEXT,
    "lv_balanceusd" TEXT,
    "lv_basecurrencyid" TEXT,
    "lv_DateofMarginCall" TEXT,
    "Lv_Deletedfromtradingplatform" TEXT,
    "Lv_Deletiondatefromtradingplatform" TEXT,
    "Lv_disabledonthetradingplatform" TEXT,
    "Lv_disablingdateonthetradingplatform" TEXT,
    "Lv_disablingreasononthetradingplatform" TEXT,
    "lv_DoubleLeverage" TEXT,
    "lv_equity" TEXT,
    "Lv_ExpirationDate" TEXT,
    "Lv_Idonaffiliatesystem" TEXT,
    "lv_is_request_info" TEXT,
    "lv_isloggedinfrommobileandroid" TEXT,
    "lv_isloggedinfrommobilehtml5" TEXT,
    "lv_isloggedinfrommobileios" TEXT,
    "lv_isloggedinfrommt4clientormobile" TEXT,
    "lv_isloggedinfromsirixstation" TEXT,
    "lv_isloggedinfromtablet" TEXT,
    "lv_isloggedinfromweb" TEXT,
    "lv_isonline" TEXT,
    "lv_LastDailyDate" TEXT,
    "lv_LastEquity" TEXT,
    "lv_LastFreeMarginUSD" TEXT,
    "Lv_LastLogin" TEXT,
    "lv_LastTradeDate" TEXT,
    "Lv_leverage" TEXT,
    "lv_LosingDaysCounter" TEXT,
    "lv_marginlevel" TEXT,
    "lv_MarginStatus" TEXT,
    "lv_numberofallpositions" TEXT,
    "lv_numberofopenedpositions" TEXT,
    "lv_OldNameTest" TEXT,
    "lv_OldPasswordTest" TEXT,
    "lv_OldTradingPlatformTest" TEXT,
    "lv_onlinesince" TEXT,
    "lv_password" TEXT,
    "lv_pl" TEXT,
    "lv_platformreadonly" TEXT,
    "Lv_TempName" TEXT,
    "lv_totaltradingamount" TEXT,
    "Lv_TPAccountLastValueDisableTPAcc" TEXT,
    "lv_TPGroupId" TEXT,
    "lv_tradingplatformid" TEXT,
    "lv_Type" TEXT,
    "lv_WinningDaysCounter" TEXT,
    "lv_tradeserverhostname" TEXT,
    "lv_tradingtype" TEXT,
    "lv_DateofLastBonus" TEXT,
    "lv_DateofLastBonus_Date" TEXT,
    "lv_DateofLastBonus_State" TEXT,
    "lv_IsNetting" TEXT,
    "lv_sendingemail" TEXT
);

-- 2.4 CRM Lv_monetarytransactionBase (109 colunas)
CREATE TABLE stg_raw.lv_monetarytransactionbase (
    "Lv_monetarytransactionId" TEXT,
    "CreatedOn" TEXT,
    "CreatedBy" TEXT,
    "ModifiedOn" TEXT,
    "ModifiedBy" TEXT,
    "CreatedOnBehalfBy" TEXT,
    "ModifiedOnBehalfBy" TEXT,
    "OwnerId" TEXT,
    "OwnerIdType" TEXT,
    "OwningBusinessUnit" TEXT,
    "statecode" TEXT,
    "statuscode" TEXT,
    "ImportSequenceNumber" TEXT,
    "OverriddenCreatedOn" TEXT,
    "TimeZoneRuleVersionNumber" TEXT,
    "UTCConversionTimeZoneCode" TEXT,
    "Lv_name" TEXT,
    "lv_accountid" TEXT,
    "Lv_AdditionalCharges" TEXT,
    "lv_AdditionalInfo" TEXT,
    "lv_affiliatetransactionid" TEXT,
    "Lv_Amount" TEXT,
    "Lv_ApprovedOn" TEXT,
    "lv_AutoApproval" TEXT,
    "Lv_Bank" TEXT,
    "Lv_BankAccountCurrency" TEXT,
    "lv_bankaccountcurrencyid" TEXT,
    "Lv_BaseCurrencyAmount" TEXT,
    "lv_basecurrencyid" TEXT,
    "Lv_BrokerBankAccountDetails" TEXT,
    "Lv_CardAcquirer" TEXT,
    "Lv_CardAcquirerReference" TEXT,
    "Lv_Cardexpirationmonth" TEXT,
    "Lv_Cardexpirationyear" TEXT,
    "Lv_CardHolderIdentity" TEXT,
    "Lv_CardHolderName" TEXT,
    "Lv_CardIssuingBank" TEXT,
    "lv_CardIssuingCountry" TEXT,
    "Lv_CardType" TEXT,
    "lv_cardtypetext" TEXT,
    "Lv_CCLast4Digits" TEXT,
    "lv_clearingresponse" TEXT,
    "Lv_Comment" TEXT,
    "lv_Commission" TEXT,
    "lv_ConversionRate" TEXT,
    "lv_ConvertedAmount" TEXT,
    "lv_CryptoCurrencyCode" TEXT,
    "lv_CryptoTransactionID" TEXT,
    "Lv_Currency" TEXT,
    "Lv_CurrencyBase" TEXT,
    "lv_customamount" TEXT,
    "lv_customftddate" TEXT,
    "lv_customusdvalue" TEXT,
    "lv_defaultcasetitle" TEXT,
    "Lv_DepositindefinedtimerangefromFTD" TEXT,
    "Lv_ExchangeRate" TEXT,
    "Lv_ExpirayDate" TEXT,
    "Lv_FirstTimeDeposit" TEXT,
    "Lv_hiddenMoney" TEXT,
    "TransactionCurrencyId" TEXT,
    "ExchangeRate" TEXT,
    "lv_hiddenmoney_Base" TEXT,
    "Lv_Idonaffiliatesystem" TEXT,
    "Lv_internalcomment" TEXT,
    "lv_internaltransactionstatus" TEXT,
    "Lv_InternalType" TEXT,
    "lv_is_request_info" TEXT,
    "lv_lastactionid" TEXT,
    "lv_lastactionresult" TEXT,
    "Lv_ManagementApproval" TEXT,
    "Lv_MethodofPayment" TEXT,
    "lv_MTTransactionOwner" TEXT,
    "lv_NetDepositUSDValue" TEXT,
    "lv_oppositeaccountid" TEXT,
    "Lv_OriginalAmount" TEXT,
    "Lv_OriginalCurrency" TEXT,
    "Lv_Paid" TEXT,
    "Lv_PaymentDetails" TEXT,
    "Lv_paymentMethod" TEXT,
    "lv_relatedtransactionid" TEXT,
    "Lv_ReportedToAffiliateSystem" TEXT,
    "Lv_RequestDate" TEXT,
    "lv_sendemail" TEXT,
    "lv_shouldnotsendemailoncreate" TEXT,
    "Lv_Status" TEXT,
    "lv_TCBonusapproved" TEXT,
    "lv_tpaccountid" TEXT,
    "lv_TradingPlatformOppositeTransactionId" TEXT,
    "lv_TradingPlatformTransactionId" TEXT,
    "Lv_TransactionApproved" TEXT,
    "lv_transactioncaseid" TEXT,
    "lv_transactiondetails" TEXT,
    "Lv_TransactionReference" TEXT,
    "lv_transfertotpaccount" TEXT,
    "Lv_Type" TEXT,
    "lv_TypeofFee" TEXT,
    "lv_updatebalancebyid" TEXT,
    "Lv_UpdateTPon" TEXT,
    "Lv_UpdateTPOnApprove" TEXT,
    "Lv_USDValue" TEXT,
    "lv_WalletID" TEXT,
    "Lv_webmoneyemail" TEXT,
    "Lv_webmoneyNumber" TEXT,
    "Lv_wiretransferBankAccountNumber" TEXT,
    "Lv_wiretransferBankAddress" TEXT,
    "Lv_wiretransferBankName" TEXT,
    "Lv_wiretransferBeneficiary" TEXT,
    "Lv_wiretransferSwiftCode" TEXT,
    "Lv_WithdrawalReason" TEXT
);

-- 2.5 Sirix Daily View (13 colunas)
CREATE TABLE stg_raw.sirix_daily_view (
    "LOGIN" TEXT,
    "TIME" TEXT,
    "GROUP" TEXT,
    "BALANCE_PREV" TEXT,
    "BALANCE" TEXT,
    "DEPOSIT" TEXT,
    "CREDIT" TEXT,
    "PROFIT_CLOSED" TEXT,
    "PROFIT" TEXT,
    "EQUITY" TEXT,
    "MARGIN" TEXT,
    "MARGIN_FREE" TEXT,
    "MODIFY_TIME" TEXT
);

-- 2.6 Sirix Trades View (28 colunas)
CREATE TABLE stg_raw.sirix_trades_view (
    "TICKET" TEXT,
    "OPEN_POSITION_ID" TEXT,
    "LOGIN" TEXT,
    "SYMBOL" TEXT,
    "DIGITS" TEXT,
    "CMD" TEXT,
    "VOLUME" TEXT,
    "OPEN_TIME" TEXT,
    "OPEN_PRICE" TEXT,
    "SL" TEXT,
    "TP" TEXT,
    "CLOSE_TIME" TEXT,
    "EXPIRATION" TEXT,
    "CONV_RATE1" TEXT,
    "CONV_RATE2" TEXT,
    "COMMISSION" TEXT,
    "COMMISSION_AGENT" TEXT,
    "SWAPS" TEXT,
    "CLOSE_PRICE" TEXT,
    "PROFIT" TEXT,
    "TAXES" TEXT,
    "COMMENT" TEXT,
    "INTERNAL_ID" TEXT,
    "MARGIN_RATE" TEXT,
    "TIMESTAMP" TEXT,
    "MODIFY_TIME" TEXT,
    "account_id" TEXT,
    "broker_id" TEXT
);

-- 2.7 Sirix Users View (36 colunas)
CREATE TABLE stg_raw.sirix_users_view (
    "LOGIN" TEXT,
    "GROUP" TEXT,
    "ENABLE" TEXT,
    "ENABLE_CHANGE_PASS" TEXT,
    "ENABLE_READONLY" TEXT,
    "PASSWORD_PHONE" TEXT,
    "NAME" TEXT,
    "COUNTRY" TEXT,
    "CITY" TEXT,
    "STATE" TEXT,
    "ZIPCODE" TEXT,
    "ADDRESS" TEXT,
    "PHONE" TEXT,
    "EMAIL" TEXT,
    "COMMENT" TEXT,
    "ID" TEXT,
    "STATUS" TEXT,
    "REGDATE" TEXT,
    "LASTDATE" TEXT,
    "LEVERAGE" TEXT,
    "AGENT_ACCOUNT" TEXT,
    "TIMESTAMP" TEXT,
    "BALANCE" TEXT,
    "PREVMONTHBALANCE" TEXT,
    "PREVBALANCE" TEXT,
    "CREDIT" TEXT,
    "INTERESTRATE" TEXT,
    "TAXES" TEXT,
    "SEND_REPORTS" TEXT,
    "USER_COLOR" TEXT,
    "EQUITY" TEXT,
    "MARGIN" TEXT,
    "MARGIN_LEVEL" TEXT,
    "MARGIN_FREE" TEXT,
    "MODIFY_TIME" TEXT,
    "CURRENCY" TEXT
);

-- ==============================================================================
-- 3. IMPORTAÇÃO DOS DADOS DE CSV
-- ==============================================================================
-- Os arquivos oficiais de PRD analisados estão fora do repositório:
-- /Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw
--
-- ATENÇÃO: crm_user_base.csv e Lv_tpaccountBase.csv contêm campos sensíveis
-- como lv_password. O bootstrap bronze não persiste esses campos, mas a carga
-- em stg_raw ainda mantém o landing bruto temporariamente. Em produção, o
-- extractor deve excluir esses campos antes de escrever o arquivo oficial.

COPY stg_raw.crm_account_base FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/crm_account_base.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');
COPY stg_raw.crm_user_base FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/crm_user_base.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');
COPY stg_raw.lv_tpaccountbase FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/Lv_tpaccountBase.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');
COPY stg_raw.lv_monetarytransactionbase FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/Lv_monetarytransactionBase.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');
COPY stg_raw.sirix_daily_view FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/sirix_daily_view.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');
COPY stg_raw.sirix_trades_view FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/sirix_trades_view.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');
COPY stg_raw.sirix_users_view FROM '/Users/arthurnariz/Developer/bd/tcc-brokerlab/stg_raw/sirix_users_view.csv' WITH (FORMAT csv, HEADER true, DELIMITER ',');

-- Higienização imediata do landing bruto para evitar persistência de senhas.
-- Essas colunas não são usadas no bootstrap bronze.
UPDATE stg_raw.crm_user_base
SET "lv_password" = NULL,
    "lv_googleauthenticatorsecretkeytemp" = NULL;

UPDATE stg_raw.lv_tpaccountbase
SET "lv_password" = NULL,
    "lv_OldPasswordTest" = NULL;
